name: 'Detect Package Changes For Turbo Mono Repo'
description: 'Detects changes in packages for Turbo Mono Repo'
author: 'Hodfords'

branding:
  icon: 'heart'
  color: 'black'

inputs:
  changeFiles:
    description: 'Change files'
    required: true
  includePackage:
    description: 'Include package'
    required: false
  apps:
    description: 'Apps paths, split by space'
    required: true
  dependencies:
    description: 'Dependencies paths, split by space'
    required: true
  workspacePath:
    description: 'Workspace path'
    required: true
  yamlConfig:
    description: 'Yaml config path'
    required: false
  currentBranch:
    description: 'Current branch'
    required: false

outputs:
  changedApps:
    description: 'List app that have changes'
  changedAppsFromYaml:
    description: 'List app that have changes'

runs:
  using: node20
  main: dist/index.js
