branch:
  develop: dev
  testing: dev
  staging: uat
  master: prod

global:
  dev:
    s3-region: ap-southeast-1
  prod:
    s3-region: eu-west-1

apps:
  - name: app1
    environment: dev
  - name: app1
    environment: prod

  - name: app2
    environment: dev
    cdn-id: abc
  - name: app2
    environment: prod
    cdn-id: xyz
